/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subscriptions_management;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import net.proteanit.sql.DbUtils;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import com.toedter.calendar.JDateChooser;
import javax.swing.JComboBox;

/**
 *
 * @author MyLau
 */
public class EmployeHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeHome
     */
    
    public boolean dataStatu;
    //String requete=
    public void getData(){
        try{

        java.sql.Statement stmt1=maConnexion.ObtenirConnexion().createStatement();
        java.sql.ResultSet resultat= stmt1.executeQuery("SELECT id, nom, prenom, date_naissance, lieu_naissance, profession, date_enregistrement, telephone FROM membres");
	    jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
	
	
       }catch(Exception e){
    	   System.out.println(e);
       }
    }
    

    public EmployeHome() {
        initComponents();
        jTDateNais.setDate(new Date());
        
        
        setLocation(8,32);
        
        getData();
        dataStatu= true;
         SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jTNom.requestFocus();
       
      }
      
    });
         pack();
    }
    Statement stmt;
    Connexion maConnexion= new Connexion();
    String table1_click;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLNom = new javax.swing.JLabel();
        jLPrenom = new javax.swing.JLabel();
        jTNom = new javax.swing.JTextField();
        jTPrenom = new javax.swing.JTextField();
        jTLieuNais = new javax.swing.JTextField();
        jLLieuNais = new javax.swing.JLabel();
        jLSexe = new javax.swing.JLabel();
        jCSexe = new javax.swing.JComboBox();
        jLDateNais = new javax.swing.JLabel();
        jTDateNais = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLTel = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jFTTel = new javax.swing.JFormattedTextField();
        jTEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBValider = new javax.swing.JButton();
        jBVider = new javax.swing.JButton();
        jBQuitter = new javax.swing.JButton();
        jSupprimer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jTSearch = new javax.swing.JTextField();
        jLTel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DES MEMBRES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails sur les membres"));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations Personnelles"));

        jLNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNom.setForeground(new java.awt.Color(255, 102, 102));
        jLNom.setText("NOM");

        jLPrenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPrenom.setForeground(new java.awt.Color(255, 102, 102));
        jLPrenom.setText("PRENOM");

        jTNom.setText(" ");
        jTNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomActionPerformed(evt);
            }
        });
        jTNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNomKeyTyped(evt);
            }
        });

        jTPrenom.setText(" ");
        jTPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrenomActionPerformed(evt);
            }
        });
        jTPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPrenomKeyTyped(evt);
            }
        });

        jTLieuNais.setText(" ");
        jTLieuNais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTLieuNaisActionPerformed(evt);
            }
        });
        jTLieuNais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTLieuNaisKeyTyped(evt);
            }
        });

        jLLieuNais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLLieuNais.setForeground(new java.awt.Color(255, 102, 102));
        jLLieuNais.setText("LIEU DE NAISSANCE");

        jLSexe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSexe.setForeground(new java.awt.Color(255, 102, 102));
        jLSexe.setText("GENRE");

        jCSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin", "Féminin" }));
        jCSexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSexeActionPerformed(evt);
            }
        });

        jLDateNais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDateNais.setForeground(new java.awt.Color(255, 102, 102));
        jLDateNais.setText("DATE NAISSANCE");

        jTDateNais.setDateFormatString("yyyy-MM-dd");
        
        jTProfession = new JTextField();
        jTProfession.setText(" ");
        
        JLabel jLPoste = new JLabel();
        jLPoste.setText("PROFESSION");
        jLPoste.setForeground(UIManager.getColor("Button.select"));
        jLPoste.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        JLabel jLDateEmb = new JLabel();
        jLDateEmb.setText("DATE D'ENREGISTREMENT");
        jLDateEmb.setForeground(UIManager.getColor("Button.select"));
        jLDateEmb.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        jTDateEnreg = new JDateChooser();
        jTDateEnreg.setDateFormatString("yyyy-MM-dd");
        
        JLabel jLStatut = new JLabel();
        jLStatut.setText("STATUT MEMBRE");
        jLStatut.setForeground(UIManager.getColor("Button.select"));
        jLStatut.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        jCStatut = new JComboBox();
        jCStatut.setModel(new DefaultComboBoxModel(new String[] {"Actif", "Inactif"}));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLNom, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLPrenom, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLSexe, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLDateNais)
        						.addComponent(jLLieuNais)
        						.addComponent(jLPoste, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
        					.addGap(38)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jTProfession, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(jTLieuNais, Alignment.LEADING)
        							.addComponent(jCSexe, Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jTNom, Alignment.LEADING)
        							.addComponent(jTPrenom, Alignment.LEADING)
        							.addComponent(jTDateNais, GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLDateEmb, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLStatut, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jCStatut, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jTDateEnreg, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLNom, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTNom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLPrenom, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTPrenom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLSexe, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jCSexe, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLDateNais, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTDateNais, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLLieuNais, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTLieuNais, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jTProfession, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLPoste, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLDateEmb, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTDateEnreg, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLStatut, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jCStatut, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Compagne"));
        
        jLNom_1 = new JLabel();
        jLNom_1.setText("NOM");
        jLNom_1.setForeground(UIManager.getColor("Button.select"));
        jLNom_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        textField = new JTextField();
        textField.setText(" ");
        
        jLPrenom_1 = new JLabel();
        jLPrenom_1.setText("PRENOM");
        jLPrenom_1.setForeground(UIManager.getColor("Button.select"));
        jLPrenom_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        textField_1 = new JTextField();
        textField_1.setText(" ");
        
        jLSexe_1 = new JLabel();
        jLSexe_1.setText("GENRE");
        jLSexe_1.setForeground(UIManager.getColor("Button.select"));
        jLSexe_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        jCSexe_1 = new JComboBox();
        jCSexe_1.setModel(new DefaultComboBoxModel(new String[] {"Feminin", "Masculin"}));
        
        jLDateNais_1 = new JLabel();
        jLDateNais_1.setText("DATE NAISSANCE");
        jLDateNais_1.setForeground(UIManager.getColor("Button.select"));
        jLDateNais_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        jTDateNais_1 = new JDateChooser();
        jTDateNais_1.setDateFormatString("yyyy-MM-dd");
        
        JLabel jLLieuNais_1 = new JLabel();
        jLLieuNais_1.setText("LIEU DE NAISSANCE");
        jLLieuNais_1.setForeground(UIManager.getColor("Button.select"));
        jLLieuNais_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        textField_2 = new JTextField();
        textField_2.setText(" ");
        
        JLabel jLPoste_1 = new JLabel();
        jLPoste_1.setText("PROFESSION");
        jLPoste_1.setForeground(UIManager.getColor("Button.select"));
        jLPoste_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        textField_3 = new JTextField();
        textField_3.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLNom_1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLPrenom_1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
        					.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLSexe_1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
        					.addComponent(jCSexe_1, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLDateNais_1, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
        					.addComponent(jTDateNais_1, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLLieuNais_1, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLPoste_1, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGap(6)
        							.addComponent(textField_3, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
        						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLNom_1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLPrenom_1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLSexe_1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jCSexe_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLDateNais_1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTDateNais_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLLieuNais_1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLPoste_1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField_3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));

        jLTel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTel.setForeground(new java.awt.Color(255, 102, 102));
        jLTel.setText("TELEPHONE");

        jLEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEmail.setForeground(new java.awt.Color(255, 102, 102));
        jLEmail.setText("E-MAIL");

        try {
            jFTTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(243)###-###-###"))); 
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTEmail.setText(" ");
        jTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opérations"));

        jBValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_save.png"))); // NOI18N
        jBValider.setText("Sauver");
        jBValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValiderActionPerformed(evt);
            }
        });

        jBVider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new_user.png"))); // NOI18N
        jBVider.setText("Nouveau");
        jBVider.setMaximumSize(new java.awt.Dimension(101, 23));
        jBVider.setMinimumSize(new java.awt.Dimension(101, 23));
        jBVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBViderActionPerformed(evt);
            }
        });

        jBQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/use_exit.png"))); // NOI18N
        jBQuitter.setText("Sortir");
        jBQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitterActionPerformed(evt);
            }
        });

        jSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_delete.png"))); // NOI18N
        jSupprimer.setText("Supprimer");
        jSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimerActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_print.png"))); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jBVider, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBValider, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBValider)
                    .addComponent(jBVider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBQuitter)
                    .addComponent(jSupprimer)
                    .addComponent(jButton1))
                .addGap(62, 62, 62))
        );

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Sexe", "DateNais", "NIF", "Poste", "DateEmb.", "Statut", "Salaire"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Recherche d'un membre"));

        jTSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTSearchKeyReleased(evt);
            }
        });

        jLTel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTel1.setForeground(new java.awt.Color(0, 51, 255));
        jLTel1.setText("ENTRER LE PRENOM");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLTel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119)
                .addComponent(jTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTel1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6.setLayout(jPanel6Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("jPAppli");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomActionPerformed

    private void jTNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_jTNomKeyTyped

    private void jTPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPrenomActionPerformed

    private void jTPrenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPrenomKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_jTPrenomKeyTyped

    private void jTLieuNaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTLieuNaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTLieuNaisActionPerformed

    private void jTLieuNaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTLieuNaisKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_jTLieuNaisKeyTyped

    private void jCSexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCSexeActionPerformed

    private void jTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEmailActionPerformed

    private void jBValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValiderActionPerformed
        // TODO add your handling code here:
        //*********************************************************
    	
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String daterecup=sdf.format(jTDateNais.getDate());
        String dateembrecup=sdf.format(jTDateEnreg.getDate());
        String nomrecup=jTNom.getText().toUpperCase().trim();
        String prenomrecup=jTPrenom.getText().trim();
        String sexerecup= jCSexe.getSelectedItem().toString();
        String lieurecup=jTLieuNais.getText().trim();
        String posterecup=jTProfession.getText().trim();
        String statutrecup=jCStatut.getSelectedItem().toString();
        String telrecup=jFTTel.getText();
        String emailrecup=jTEmail.getText().trim();
        // Partenaire infos
        String pnomrecup = textField.getText().toUpperCase().trim();
        String pprenomrecup = textField_1.getText().trim();
        String psexerecup = jCSexe_1.getSelectedItem().toString();
        String pdaterecup = sdf.format(jTDateNais_1.getDate());
        String plieurecup = textField_2.getText().trim();
        String pposterecup = textField_3.getText().trim();
        
        if(jTNom.getText().trim().length()>0 && jTPrenom.getText().trim().length()>0 && daterecup.length()>0
            && jTLieuNais.getText().trim().length()>0 && jTProfession.getText().trim().length()>0 && jFTTel.getText().trim().length()>0 && jTEmail.getText().trim().length()>0){

        if(dataStatu==true){
        	String requete = "";
            try{
            requete="INSERT INTO membres(nom, prenom, sexe, date_naissance, lieu_naissance, profession, date_enregistrement,statut_membre, telephone, email) value ('"+nomrecup+"','"+prenomrecup+"','"+sexerecup+"','"+daterecup+"','"+lieurecup+"','"+posterecup+"','"+dateembrecup+"','"+statutrecup+"','"+telrecup+"','"+emailrecup+"')";
            stmt=maConnexion.ObtenirConnexion().createStatement();
            stmt.executeUpdate(requete, Statement.RETURN_GENERATED_KEYS);
            
         // Retrieve the last inserted ID
            ResultSet generatedKeys = stmt.getGeneratedKeys();
            int lastInsertedId = -1;
            if (generatedKeys.next()) {
            	lastInsertedId = generatedKeys.getInt(1);
            }
            
            requete = "INSERT INTO membres(nom, prenom, sexe, date_naissance, lieu_naissance, profession, date_enregistrement, statut_membre, telephone, email, partenaire_avec) value ('"+pnomrecup+"','"+pprenomrecup+"','"+psexerecup+"','"+pdaterecup+"','"+plieurecup+"','"+pposterecup+"','"+dateembrecup+"','"+statutrecup+"','"+telrecup+"','"+emailrecup+"','"+lastInsertedId+"')";
            stmt.executeUpdate(requete);
            
            JOptionPane.showMessageDialog(null,"Enregistrement réussi!");
           
        jTNom.setText("");
        jTPrenom.setText("");
        jCSexe.setSelectedItem("Masculin");
        jTLieuNais.setText("");
        jCStatut.setSelectedItem("Actif");
        jTProfession.setText("");
        jFTTel.setText(null);
        jTEmail.setText("");
        jTDateNais.setDate(new Date());
        jTDateEnreg.setDate(new Date());
        
        textField.setText("");
        textField_1.setText("");
        jCSexe_1.setSelectedItem("Feminin");
        jTDateNais_1.setDate(new Date());
        textField_2.setText("");
        textField_3.setText("");
            }catch(SQLException | HeadlessException e){
                //JOptionPane.showMessageDialog(null,e);
                JOptionPane.showMessageDialog(null, "Veuillez vérifier l'ID!");
            }
        }else{
            String requete="UPDATE membres  SET nom='"+nomrecup+"', prenom='"+prenomrecup+"', sexe='"+sexerecup+"', date_naissance='"+daterecup+"', "
                 + "lieunais='"+lieurecup+"', profeession='"+posterecup+"', date_enregistrement='"+dateembrecup+""
                 + "', statut_membre='"+statutrecup+"', telephone='"+telrecup+"', email='"+emailrecup+"' where id='"+table1_click+"'";

      try{
            stmt =maConnexion.ObtenirConnexion().createStatement();
            stmt .executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Modification réussie!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
            
        }
        getData();
        }else{
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs!");
        }   
       
    }//GEN-LAST:event_jBValiderActionPerformed

    private void jBViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBViderActionPerformed
        // TODO add your handling code here:
        dataStatu=true;
        jTNom.setText("");
        jTPrenom.setText("");
        jCSexe.setSelectedItem("Masculin");
        jTLieuNais.setText("");
        jCStatut.setSelectedItem("Contrat Tps Plein");
        jTProfession.setText("");
        jFTTel.setText(null);
        jTEmail.setText("");
        jTDateNais.setDate(new Date());
        jTDateEnreg.setDate(new Date());
        
        textField.setText("");
        textField_1.setText("");
        jCSexe_1.setSelectedItem("Feminin");
        jTDateNais_1.setDate(new Date());
        textField_2.setText("");
        textField_3.setText("");
        SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jTNom.requestFocus();
       
      }
      
    });
    }//GEN-LAST:event_jBViderActionPerformed

    private void jBQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitterActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jBQuitterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dataStatu=false;
        try{
            int row=jTable1.getSelectedRow();
            table1_click=(jTable1.getModel().getValueAt(row,0).toString());
            java.sql.Statement stmt1=maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultat= stmt1.executeQuery("SELECT * FROM membres WHERE id='"+table1_click+"'");

            if(resultat.next()){
                jTNom.setText(resultat.getString("nom"));
                jTPrenom.setText(resultat.getString("prenom"));
                jCSexe.setSelectedItem(resultat.getString("sexe"));
                jTDateNais.setDate(resultat.getDate("date_naissance"));
                jTLieuNais.setText(resultat.getString("lieu_naissance"));
                jCStatut.setSelectedItem(resultat.getString("statut_membres"));
                jTProfession.setText(resultat.getString("profession"));
                jTDateEnreg.setDate(resultat.getDate("date_enregistrement"));
                jCStatut.setSelectedItem(resultat.getString("statut_membre"));
                jFTTel.setText(resultat.getString("telephone"));
                jTEmail.setText(resultat.getString("email"));
            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupprimerActionPerformed
        // TODO add your handling code here:
        if(jTNom.getText().trim().length()>0 && jTPrenom.getText().trim().length()>0
                && jTLieuNais.getText().trim().length()>0 && jTProfession.getText().trim().length()>0 && jFTTel.getText().length()>0 && jTEmail.getText().trim().length()>0){ 
            String requete="DELETE FROM membres WHERE id='"+table1_click+"'";
        try{
            stmt=maConnexion.ObtenirConnexion().createStatement();
            stmt.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Suppresion réussie!");
           
               
      }                                           
      catch(SQLException ex){
            System.err.println(ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un membre!");
      
            
        }
       
        jTNom.setText("");
        jTPrenom.setText("");
        jCSexe.setSelectedItem("Masculin");
        jTLieuNais.setText("");
        jCStatut.setSelectedItem("Actif");
        jTProfession.setText("");
        jFTTel.setText(null);
        jTEmail.setText("");
        jTDateNais.setDate(new Date());
        jTDateEnreg.setDate(new Date());
        getData();
    }//GEN-LAST:event_jSupprimerActionPerformed

    private void jTSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTSearchKeyReleased
        // TODO add your handling code here:

        dataStatu=false;
        
        try{
        	
            java.sql.Statement stmt1=maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultat= stmt1.executeQuery("SELECT * FROM membres where nom LIKE '" + jTSearch.getText().trim() + "%'");
            jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
	
        }catch(Exception e){
	
	
        }  
    }//GEN-LAST:event_jTSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        final String daterecup=sdf.format(jTDateEnreg.getDate());
        final String dateNais=sdf.format(jTDateNais.getDate());
        
        if(jTNom.getText().trim().length()>0 && jTPrenom.getText().trim().length()>0
                && jTLieuNais.getText().trim().length()>0 && jTProfession.getText().trim().length()>0 && jFTTel.getText().length()>0 && jTEmail.getText().trim().length()>0){
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Printable() {
 
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }
         
    //Image
                /*BufferedImage image = ImageIO.read(new File(adresseImage));
                graphics.drawImage(image, 0, 0, null);*/
                
    //Image
        int marge=30;
        int x = (int)pageFormat.getImageableX();
        int y = (int)pageFormat.getImageableY();
                 
        graphics.setFont(new Font("Times new roman", Font.BOLD, 20));
        graphics.setColor(Color.BLACK);
        graphics.drawString("                            FICHE DU MEMBRE\n", x + marge, y + marge);
 
        graphics.drawLine(100, 40, 470, 40);
    
    
        graphics.setFont(new Font("Times New Roman", Font.LAYOUT_LEFT_TO_RIGHT, 18));
        graphics.drawString(" *Nom", 130, 80);        
        graphics.drawString(jTNom.getText(), 350, 80);
        
        graphics.drawString(" *Prénom", 130, 110);
        graphics.drawString(jTPrenom.getText(), 350, 110);
        
        graphics.drawString(" *Sexe", 130, 140);
        graphics.drawString((String) jCSexe.getSelectedItem(), 350, 140);
        
        graphics.drawString(" *Date Naissance", 130, 170);
        graphics.drawString(dateNais, 350, 170);
        
        graphics.drawString(" *Lieu", 130, 200);
        graphics.drawString(jTLieuNais.getText(), 350, 200);
        
        graphics.drawString(" *Statut", 130, 230);
        graphics.drawString(jCStatut.getSelectedItem().toString(), 350, 230);
        
        graphics.drawString(" *Profession", 130, 270);
        graphics.drawString(jTProfession.getText(), 350, 270);
             
        graphics.drawString(" *Poste", 130, 300);
        graphics.drawString(jTProfession.getText(), 350, 300);
        
        graphics.drawString(" *Date Embauche", 130, 360);
        graphics.drawString(daterecup, 350, 360);
        
        graphics.drawString(" *Statut", 130, 390);
        graphics.drawString((String) jCStatut.getSelectedItem(), 350, 390);
        
        graphics.drawString(" *Téléphone", 130, 420);
        graphics.drawString(jFTTel.getText(), 350, 420);
        
        graphics.drawString(" *Email", 130, 450);
        graphics.drawString(jTEmail.getText(), 350, 450);

        return PAGE_EXISTS;
            }
 
        });
boolean doPrint = job.printDialog();
if(doPrint) {
    try {
         
        job.print();
    }
    catch (PrinterException e1) {
            JOptionPane.showMessageDialog(null, e1);
    }
}}else{
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un membre!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBQuitter;
    private javax.swing.JButton jBValider;
    private javax.swing.JButton jBVider;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCSexe;
    private javax.swing.JFormattedTextField jFTTel;
    private javax.swing.JLabel jLDateNais;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLLieuNais;
    private javax.swing.JLabel jLNom;
    private javax.swing.JLabel jLPrenom;
    private javax.swing.JLabel jLSexe;
    private javax.swing.JLabel jLTel;
    private javax.swing.JLabel jLTel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSupprimer;
    private com.toedter.calendar.JDateChooser jTDateNais;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTLieuNais;
    private javax.swing.JTextField jTNom;
    private javax.swing.JTextField jTPrenom;
    private javax.swing.JTextField jTSearch;
    private javax.swing.JTable jTable1;
    private JTextField jTProfession;
    private JDateChooser jTDateEnreg;
    private JComboBox jCStatut;
    private JLabel jLNom_1;
    private JTextField textField;
    private JLabel jLPrenom_1;
    private JTextField textField_1;
    private JLabel jLSexe_1;
    private JComboBox jCSexe_1;
    private JLabel jLDateNais_1;
    private JTextField textField_2;
    private JTextField textField_3;
    private JDateChooser jTDateNais_1;
}
