/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subscriptions_management;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.TitledBorder;
import javax.swing.border.EtchedBorder;
import java.awt.Color;
import javax.swing.JSeparator;
import javax.swing.JMenuItem;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author MyLau
 */
@SuppressWarnings("serial")
public class GestionRH_View extends javax.swing.JFrame {

    /**
     * Creates new form GestionRH_View
     */
    public GestionRH_View() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("icone_jar.png")).getImage());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       // setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAppli = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPAppli.setBackground(new java.awt.Color(204, 255, 204));
        jPAppli.setBorder(new TitledBorder(new TitledBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null), "SYSTEME DE GESTION DES FINANCES", TitledBorder.CENTER, TitledBorder.TOP, null, new Color(15, 36, 255)), "SYSTEME DE GESTION DES FINANCES", TitledBorder.CENTER, TitledBorder.TOP, null, new Color(15, 36, 255)), "SYSTEME DE GESTION DES FINANCES", TitledBorder.CENTER, TitledBorder.TOP, null, new Color(15, 36, 255))); // NOI18N
        jPAppli.setName("jPAppli"); // NOI18N

        javax.swing.GroupLayout jPAppliLayout = new javax.swing.GroupLayout(jPAppli);
        jPAppli.setLayout(jPAppliLayout);
        jPAppliLayout.setHorizontalGroup(
            jPAppliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        
        jPAppliLayout.setVerticalGroup(
            jPAppliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Employe 32.png"))); // NOI18N
        jMenu1.setText("MEMBRES");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Accueil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("Liste membres");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/avance 32.png"))); // NOI18N
        jMenu4.setText("TRANSACTIONS");

        jMenuItem4.setText("Accueil");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);
        
        JSeparator separator = new JSeparator();
        jMenu4.add(separator);
        
        JMenuItem mntmNewMenuItem = new JMenuItem("Parametres");
        mntmNewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        		SettingsHome settingsH = new SettingsHome();
        		settingsH.setVisible(true);
        	}
        });
        jMenu4.add(mntmNewMenuItem);

        jMenu5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/divers 32.png"))); // NOI18N
        jMenu5.setText("RAPPORTS");
        jMenuBar1.add(jMenu5);
        
        mntmNewMenuItem_1 = new JMenuItem("Rapport general");
        mntmNewMenuItem_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        		// Launch general report
        		ListeTransaction listTrans = new ListeTransaction();
            	jPAppli.removeAll();
                jPAppli.repaint();
                jPAppli.add(listTrans);
                listTrans.show();
        	}
        });
        jMenu5.add(mntmNewMenuItem_1);
        
        mnNewMenu = new JMenuItem("Rapport personnalisé ");
        mnNewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        		SpecialReport spReport = new SpecialReport();
            	jPAppli.removeAll();
                jPAppli.repaint();
                jPAppli.add(spReport);
                spReport.show();
        	}
        });
        jMenu5.add(mnNewMenu);
        
        reportDebiteurs = new JMenuItem("Rapport debiteurs");
        reportDebiteurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        		DebiteursReport debiteursReport = new DebiteursReport();
            	jPAppli.removeAll();
                jPAppli.repaint();
                jPAppli.add(debiteursReport);
                debiteursReport.show();
        	}
        });
        jMenu5.add(reportDebiteurs);
        
        mntmNewMenuItem_2 = new JMenuItem("Rapport crediteurs");
        mntmNewMenuItem_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		CrediteursReport crediteursReport = new CrediteursReport();
            	jPAppli.removeAll();
                jPAppli.repaint();
                jPAppli.add(crediteursReport);
                crediteursReport.show();
        	}
        });
        jMenu5.add(mntmNewMenuItem_2);

        jMenu6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fermer 32.png"))); // NOI18N
        jMenu6.setText("QUITTER");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAppli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPAppli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPAppli.getAccessibleContext().setAccessibleName("jPAppli");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        EmployeHome addEmp=new EmployeHome();
        jPAppli.removeAll();
        jPAppli.repaint();
        jPAppli.add(addEmp);
        addEmp.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ListeEmploye listeEmp=new ListeEmploye();
        jPAppli.removeAll();
        jPAppli.repaint();
        jPAppli.add(listeEmp);
        listeEmp.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here
        TransactionsHome addAvance = new TransactionsHome();
        jPAppli.removeAll();
        jPAppli.repaint();
        jPAppli.add(addAvance);
        addAvance.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionRH_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionRH_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionRH_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionRH_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionRH_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPAppli;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private JMenuItem mntmNewMenuItem_1;
    private JMenuItem mnNewMenu;
    private JMenuItem reportDebiteurs;
    private JMenuItem mntmNewMenuItem_2;
}
