/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subscriptions_management;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author MyLau
 */
@SuppressWarnings("serial")
public class SpecialReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListeEmploye
     */
    Statement stmt;
    Connexion maConnexion=new Connexion();
    float cumulTotal = (float) 0.0;
    float capitalInitial = (float) 0.0;
    float capitalActuel = (float) 0.0;
    float totalDebit = (float) 0.0, totalCredit = (float) 0.0;
    DefaultTableModel tableModel;
    
    
    
    public SpecialReport() {
    	
        initComponents();
        
        getAllDebitTotal();
        getAllCreditTotal();
        
        // Get IC 
    	String requeteIC = "select * from settings";
        try {
        	stmt=maConnexion.ObtenirConnexion().createStatement();
			ResultSet resultat= stmt.executeQuery(requeteIC);
			while(resultat.next()) {
				capitalInitial = resultat.getFloat("current_initial_capital");
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        // Display credit and debit balance
        lblNewLabel.setText("Balance = "+totalDebit+" (D) - "+totalCredit+" (C)"+ " = "+(totalDebit-totalCredit));
        
        setLocation(8,32);

        String requeteListeLivre = "select * from transactions_table";
        
        try{
            ResultSet resultat= stmt.executeQuery(requeteListeLivre);
            while(resultat.next()){
            	cumulTotal = Float.parseFloat(resultat.getString("interet")) + cumulTotal;
                detailsLabel.setText("Interet actuel (IA) "+cumulTotal+" + Capital Initial "+capitalInitial+" = C.A "+(cumulTotal+capitalInitial));
            }
        } catch(SQLException ex) {
        	System.out.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rapport personnalisé"));
        
        // Create the table model & fulfill with data
        String[] columnNames = {"Date", "Id Op", "Libelle", "Debit", "Credit", "Solde"};
        tableModel = new DefaultTableModel(columnNames, 0);
        /** Fetching data **/
        
        try {
        	java.sql.Statement stmt1= maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultSet= stmt1.executeQuery("SELECT * FROM transactions_table");

            while (resultSet.next()) {
                // Retrieve values from the result set
                String date = resultSet.getString("date");
                int id = resultSet.getInt("id");
                String libelle = resultSet.getString("libelle");
                float montant = resultSet.getFloat("montant");
                String person = resultSet.getString("personne");

                // Calculate Debit, Credit, and Solde based on the Libelle value
                float debit = libelle.equals("Débit") ? montant : 0;
                float credit = libelle.equals("Crédit") ? montant : 0;
                
                String[] parts = person.split(" ");

                // Add a row to the table model
                Object[] row = {date, id, libelle+" par "+parts[1]+" "+parts[2], debit, credit, 0};
                tableModel.addRow(row);
            }

            resultSet.close();
            stmt1.close();
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
     // Update the Solde values in the table model
        float solde = 0;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            float debit = (float) tableModel.getValueAt(i, 3);
            float credit = (float) tableModel.getValueAt(i, 4);
            solde = solde - debit + credit;
            tableModel.setValueAt(solde, i, 5);
        }

        // Create the table with the table model
        TableEmp = new JTable(tableModel);
        
        /** Fetching data **/
        TableEmp.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(TableEmp);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/printer.png"))); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        detailsLabel = new JLabel("Chargement des données...");
        
        lblNewLabel = new JLabel("Balance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(70)
        			.addComponent(detailsLabel, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jButton1)
        			.addGap(147)
        			.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );
        
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        			.addComponent(jButton1)
        			.addComponent(detailsLabel, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addComponent(lblNewLabel))
        );
        
        jPanel2.setLayout(jPanel2Layout);
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Liste des transactions");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            TableEmp.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impression ", e.getMessage());
        }
    }
    //GEN-LAST:event_jButton1ActionPerformed
    
    private void getAllDebitTotal() {
        try {
            java.sql.Statement stmt1 = maConnexion.ObtenirConnexion().createStatement();
            String query = "SELECT ROUND(SUM(montant), 2) FROM transactions_table WHERE libelle = 'Débit'";
            java.sql.ResultSet resultat = stmt1.executeQuery(query);

            while (resultat.next()) {
                totalDebit = resultat.getFloat(1);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    private void getAllCreditTotal() {
    	try {
            java.sql.Statement stmt1 = maConnexion.ObtenirConnexion().createStatement();
            String query = "SELECT ROUND(SUM(montant), 2) FROM transactions_table WHERE libelle = 'Crédit'";
            java.sql.ResultSet resultat = stmt1.executeQuery(query);

            while (resultat.next()) {
            	totalCredit = resultat.getFloat(1);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    
    private javax.swing.JTable TableEmp;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel detailsLabel;
    private JLabel lblNewLabel;
}
